import type { Book } from "./types";

// Spine colors are picked per book, not taken from real covers. Ratings are placeholders.
export const BOOKS: Book[] = [
	{
		id: "competing-against-luck",
		title: "Competing Against Luck",
		author: "Christensen et al.",
		cover: "https://covers.openlibrary.org/b/id/8138391-L.jpg",
		spineColor: "#4a5568",
		depth: 20,
		rating: 0,
	},
	{
		id: "apple-in-china",
		title: "Apple in China",
		author: "Patrick McGee",
		cover: "https://covers.openlibrary.org/b/id/15151586-L.jpg",
		spineColor: "#1f2430",
		depth: 26,
		rating: 5,
	},
	{
		id: "shoe-dog",
		title: "L'arte della vittoria",
		author: "Phil Knight",
		cover: "https://covers.openlibrary.org/b/id/8858487-L.jpg",
		spineColor: "#7c4430",
		depth: 30,
		rating: 3,
	},
	{
		id: "that-will-never-work",
		title: "That Will Never Work",
		author: "Marc Randolph",
		cover: "https://covers.openlibrary.org/b/id/10663066-L.jpg",
		spineColor: "#8a4a3a",
		depth: 22,
		rating: 5,
	},
	{
		id: "working-backwards",
		title: "Working Backwards",
		author: "Bryar & Carr",
		cover: "https://covers.openlibrary.org/b/id/10297403-L.jpg",
		spineColor: "#22344a",
		depth: 32,
		rating: 3,
	},
	{
		id: "street-fight",
		title: "Street Fight",
		author: "Sadik-Khan",
		cover: "https://covers.openlibrary.org/b/id/13079426-L.jpg",
		spineColor: "#3a3f47",
		depth: 24,
		rating: 5,
	},
	{
		id: "articulating-design-decisions",
		title: "Articulating Design Decisions",
		author: "Tom Greever",
		cover: "https://covers.openlibrary.org/b/id/8253809-L.jpg",
		spineColor: "#3f5a52",
		depth: 18,
		rating: 4,
	},
	{
		id: "the-mom-test",
		title: "The Mom Test",
		author: "Rob Fitzpatrick",
		cover: "https://covers.openlibrary.org/b/id/10660557-L.jpg",
		spineColor: "#E22973",
		depth: 16,
		rating: 5,
	},
	{
		id: "curbing-traffic",
		title: "Curbing Traffic",
		author: "Bruntlett & Bruntlett",
		cover: "https://covers.openlibrary.org/b/id/11606339-L.jpg",
		spineColor: "#7281B0",
		depth: 22,
		rating: 5,
	},
	{
		id: "well-designed",
		title: "Well-Designed",
		author: "Jon Kolko",
		cover: "https://covers.openlibrary.org/b/id/14385148-L.jpg",
		spineColor: "#6e4a52",
		depth: 20,
		rating: 4,
	},
	{
		id: "user-friendly",
		title: "User Friendly",
		author: "Kuang & Fabricant",
		cover: "https://covers.openlibrary.org/b/id/10174106-L.jpg",
		spineColor: "#453a5c",
		depth: 26,
		rating: 1,
	},
	{
		id: "atomic-habits",
		title: "Atomic Habits",
		author: "James Clear",
		cover: "https://covers.openlibrary.org/b/id/12539702-L.jpg",
		spineColor: "#B67A5A",
		depth: 24,
		rating: 5,
	},
];
